spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    url: jdbc:mysql://localhost:3306/db
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: juzunoglualihan@gmail.com
    password: ${MAIL_SENDER_TOKEN}
    port: '587'

  kafka:
    topic:
      name: email_topics

    consumer:
      bootstrap-servers: localhost:9092
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  task:
    execution:
      pool:
        size: 10